balena-io/pinejs

- src/sbvr-api/sbvr-utils.d.ts
> Add typing for hash comparisons

- src/sbvr-api/permissions.d.ts
- src/sbvr-api/sbvr-utils.d.ts
> Expose actor type and add getApiKeyPermissions typing

- src/sbvr-api/sbvr-utils.coffee
> Use a default message for any database errors not explicitly rewritten

- package.json
> Add a prepare script so it is possible to install via git

- tsconfig.json
> Skip typescript lib checking, fixing git install in some ts projects

- src/config-loader/config-loader.ts
- src/migrator/migrator.ts
- src/sbvr-api/sbvr-utils.coffee
> Add `initSqlPath`/`initSql` which are run only on first model execution

- src/sbvr-api/sbvr-utils.d.ts
- src/sbvr-api/uri-parser.ts
> Merge hook/odata request types as they're the same

- src/sbvr-api/sbvr-utils.coffee
> Remove unnecessary `do` block

- package.json
- src/sbvr-api/permissions.coffee
- src/sbvr-api/sbvr-utils.coffee
- src/sbvr-api/uri-parser.ts
Depends-on: https://github.com/resin-io-modules/odata-parser/pull/27
> Update odata-parser to the pegjs version

- build/config.coffee
- docs/GettingStarted.md
- package.json
- src/config-loader/config-loader.ts
> Switch to `coffeescript` instead of `coffee-script`

- build/browser.coffee
- build/config.coffee
- package.json
> Remove unused ometa-js dependency

- package.json
- src/sbvr-api/permissions.coffee
> Optimise `memoizedGetConstrainedModel`

- package.json
- src/sbvr-api/permissions.coffee
> Support stripping explicit alias nodes

- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.coffee
- src/sbvr-api/uri-parser.ts
> Avoid bluebird catch sugar for performance

- src/sbvr-api/permissions.coffee
> Merge concat and uniq into union for `checkPermissions`

- src/sbvr-api/permissions.coffee
> Avoid unnecessary duplicated call to `addRelationshipBypasses`

- package.json
- src/sbvr-api/uri-parser.ts
> Update to odata-to-abstract-sql v3.0.0

- src/sbvr-api/permissions.coffee
> Make the $bypass version of definition based tables bypass permissions

- src/sbvr-api/sbvr-utils.coffee
> Use Promise.method instead of Promise.try

- src/sbvr-api/permissions.coffee
> Minor code cleanup in the permissions module

- src/sbvr-api/sbvr-utils.d.ts
- src/sbvr-api/uri-parser.ts
- typings/odata-parser.d.ts
> Add typings for odata-parser

- Gruntfile.coffee
- src/extended-sbvr-parser/extended-sbvr-parser.ts
- src/sbvr-api/sbvr-utils.d.ts
- tsconfig.json
- typings/sbvr-parser.d.ts
> Add types for sbvr-parser and use es6 exports for extended-sbvr-parser

- src/sbvr-api/control-flow.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/sbvr-utils.coffee
> Fix rolling back req hooks

- tsconfig.json
> Re-add `rootDir` that was accidentally removed

- package.json
- src/sbvr-api/permissions.ts
- src/sbvr-api/uri-parser.ts
> Update `odata-to-abstract-sql` to pick up improved typings

- src/sbvr-api/sbvr-utils.coffee
> Fix require path

- src/sbvr-api/odata-response.ts
- src/sbvr-api/sbvr-utils.ts
> Extract odata response

- src/sbvr-api/sbvr-utils.ts
> Drop unnecessary req.hooks usage

- src/sbvr-api/sbvr-utils.ts
> Switch to a single module level models lookup instead of multiple

- src/sbvr-api/uri-parser.ts
> Use `?` to check for complex urls as it's more accurate than `$`

- package.json
- src/config-loader/env.ts
- src/database-layer/db.ts
> Update pg to ^7.8.1

- src/database-layer/db.ts
> Add support for read-only transactions for postgres/mysql backends

- src/database-layer/db.ts
> Only print the error message on pool errors

- package.json
- src/config-loader/config-loader.ts
> Allow any importable config file type rather than just JSON

- src/config-loader/config-loader.ts
> Allow specifying absolute paths in the config

- src/config-loader/config-loader.ts
- src/sbvr-api/sbvr-utils.ts
> Allow specifying the abstract sql directly in the config

- src/sbvr-api/sbvr-utils.ts
- src/sbvr-compiler/odata-metadata-generator.ts
> Switch odata-metadata-generator to using an abstract sql model

- src/sbvr-api/sbvr-utils.ts
> Only validate the model if the query affected at least 1 row

- circle.yml
> Add node 12 to the circle tests

- package.json
- src/sbvr-api/abstract-sql.ts
> Fix possible null error when using a parameter alias with no value

- package.json
- src/sbvr-api/abstract-sql.ts
> Fix `getMemoizedCompileRule` not correctly memoizing

- src/sbvr-api/sbvr-utils.ts
> Memoize `resolveNavigationResource`

- src/sbvr-api/odata-response.ts
> Add basic support for non-number fields in __metadata.uri

- package.json
- src/migrator/migrator.ts
- src/sbvr-api/permissions.ts
> Update lodash types

- package.json
- src/sbvr-api/permissions.ts
Linked to https://github.com/balena-io-modules/odata-to-abstract-sql/pull/39 and https://github.com/balena-io-modules/abstract-sql-compiler/pull/57
> Update the alias instead of stripping for non-field nodes

- src/config-loader/config-loader.ts
- src/database-layer/db.ts
- src/migrator/migrator.ts
- src/sbvr-api/control-flow.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/sbvr-utils.ts
> Use `PromiseLike` to be more accepting with promise returning callbacks

- src/sbvr-api/sbvr-utils.ts
> Remove unnecessary `process.env` accesses

- src/sbvr-api/uri-parser.ts
>  Remove unused odata options to improve cache hits

- src/config-loader/config-loader.ts
> ✨: Support TS migrations

- src/sbvr-api/cached-compile.ts
> Clear the cache upon persisting it to disk

- package.json
- src/sbvr-api/odata-response.ts
- src/sbvr-api/uri-parser.ts
> Add caching of odata that uses parameter aliases

- src/sbvr-api/cached-compile.ts
This means the cache will also be freed in the cache hit case
> Schedule clearing compile cache on any use

- src/sbvr-api/sbvr-utils.ts
> Return a more accurate 409 status for constraint errors

- src/sbvr-api/sbvr-utils.ts
> Only send the error message as the response body for constraint errors

- src/sbvr-api/sbvr-utils.ts
> Correctly use the database table name for prettifying constraint errors

- src/config-loader/config-loader.ts
- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
> Use string.split with a limit where relevant

- src/sbvr-api/permissions.ts
> Reuse a single permission error to reduce cached size

- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
> Remove duplicated stack trace printing

- src/database-layer/db.ts
* Run tx event handlers asynchronously
* Clear queued tx event handlers once they've been scheduled to run
* Immediately run tx event handlers if the tx event has already triggered
> Improve tx event handlers

- src/migrator/migrator.ts
This is used in https://github.com/balena-io/pinejs/pull/264 to allow automatic migration to 11.x
> Switch to SQL migrations to enable migrating internal models

- src/migrator/migrator.ts
- src/sbvr-api/permissions.ts
> Add missing "modified at" migrations

- src/database-layer/db.ts
> Avoid allocations when clearing tx listeners

- src/config-loader/config-loader.ts
- src/data-server/SBVRServer.coffee
- src/database-layer/db.ts
- src/express-emulator/express.coffee
- src/http-transactions/transactions.coffee
- src/migrator/migrator.ts
- src/passport-pinejs/passport-pinejs.ts
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/control-flow.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
- src/server-glue/module.ts
- src/server-glue/server.ts
> Import bluebird as Bluebird instead of Promise

- src/sbvr-api/odata-response.ts
> Fix missing `await`

- build/browser.ts
- build/module.ts
- build/server.ts
- src/bin/odata-compiler.ts
- src/bin/sbvr-compiler.ts
- src/config-loader/config-loader.ts
- src/database-layer/db.ts
- src/migrator/migrator.ts
- src/odata-metadata/odata-metadata-generator.ts
- src/passport-pinejs/passport-pinejs.ts
- src/pinejs-session-store/pinejs-session-store.ts
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/cached-compile.ts
- src/sbvr-api/control-flow.ts
- src/sbvr-api/errors.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
- src/server-glue/module.ts
- src/server-glue/server.ts
> Fixes for resin-lint 3.x

- src/config-loader/config-loader.ts
> Move permissions back to being imported after sbvr-utils

- src/sbvr-api/sbvr-utils.ts
> ✨: Add an `ERROR` handler in resource hooks

- circle.yml
> CI: Remove circleci publish in favor of balenaCI

- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
> 🔒: Only allow one credential to provide permissions for the request

- src/sbvr-api/uri-parser.ts
> Ensure request.values is an object rather than nullish

- src/migrator/migrator.ts
- src/sbvr-api/control-flow.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
- src/server-glue/module.ts
- src/server-glue/server.ts
> Make wider use of async/await

- src/sbvr-api/sbvr-utils.ts
> Fix fetching sbvr-types version

- package.json
- src/extended-sbvr-parser/extended-sbvr-parser.ts
- typings/sbvr-parser.d.ts
Update lf-to-abstract-sql from 3.2.3 to 3.2.6
Update odata-to-abstract-sql from 4.4.5 to 4.4.6
Update sbvr-parser from 0.2.8 to 1.0.1
> Update to @balena/sbvr-parser 1.x

- Gruntfile.ts
- build/config.ts
- src/bin/odata-compiler.ts
- src/bin/sbvr-compiler.ts
- src/config-loader/config-loader.ts
- src/database-layer/db.ts
- src/migrator/migrator.ts
- src/odata-metadata/odata-metadata-generator.ts
- src/passport-pinejs/passport-pinejs.ts
- src/pinejs-session-store/pinejs-session-store.ts
- src/sbvr-api/cached-compile.ts
- src/sbvr-api/control-flow.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
- src/server-glue/module.ts
- src/server-glue/sbvr-loader.ts
- src/server-glue/server.ts
- typings/memoizee.d.ts
> Make use of `import type`

- package.json
- src/sbvr-api/permissions.ts
- src/sbvr-api/uri-parser.ts
Update odata-parser from 1.4.1 to 1.0.0
> Update to @balena/odata-parser 2.x

- package.json
- src/sbvr-api/sbvr-utils.ts
- typings/lf-to-abstract-sql.d.ts
Depends on #367 
Update lf-to-abstract-sql from 3.2.3 to 4.0.0
> Update to @balena/lf-to-abstract-sql 4.x

- src/data-server/sbvr-server.js
- src/http-transactions/transactions.js
> Convert javascript files to async/await

- src/express-emulator/express.js
- src/migrator/migrator.ts
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/control-flow.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
- src/server-glue/module.ts
> More async/await conversion

- package.json
> Add missing and remove unused dependencies

- package.json
- src/sbvr-api/permissions.ts
- src/sbvr-api/uri-parser.ts
Depends on https://github.com/balena-io-modules/odata-to-abstract-sql/pull/63/files
> Optimize rewriting relationships for the canAccess optimization

- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
Example usage: https://github.com/balena-io/open-balena-api/pull/265
> Automatically fetch affected ids when possible (postgres only)

- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
See: https://www.flowdock.com/app/rulemotion/resin-tech/threads/CJ0OxldLkgX3R0raiP-Zht4yk-a
> Fetch affected ids only once per request

- src/data-server/sbvr-server.js
> Clean up sbvr-server

- src/config-loader/config-loader.ts
- src/data-server/sbvr-server.js
- src/database-layer/db.ts
- src/express-emulator/express.js
- src/migrator/migrator.ts
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
> Improve compatibility with async/await stack traces

- src/sbvr-api/abstract-sql.ts
> Fix `resolveOdataBind`

- package.json
- src/pinejs-session-store/pinejs-session-store.ts
Update pinejs-client-core from 6.1.0 to 6.5.0
Update typed-error from 3.2.0 to 3.2.1
> Update pinejs-client-core to add support for $count sugar

- package.json
- src/sbvr-api/permissions.ts
Update pinejs-client-core from 6.5.0 to 6.6.0
> Update pinejs-client-core and make use of improved typings

- package.json
- src/sbvr-api/permissions.ts
Update pinejs-client-core from 6.6.1 to 6.7.0
> Update pinejs-client-core to 6.7.0

- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
> Add a specific error type for transaction closed errors and handle them

- src/sbvr-api/sbvr-utils.ts
This simplifies the implementation of internal api calls via `runURI`
and will allow async stack traces across internal calls with a future
major bump
> Separate running the odata request from the expressjs handler

- src/sbvr-api/sbvr-utils.ts
> Improve typing of getAffectedIds

- src/data-server/sbvr-server.js
- src/http-transactions/transactions.js
> Convert some bluebird usage to native promises

- src/database-layer/db.ts
> Separate the web sql wrapper for async support from the WebSqlTx class

- src/database-layer/db.ts
> Fix `TransactionClosedError` extends type

- src/database-layer/db.ts
This is only handled locally by requiring any statements to be
read-only but it's useful for websql and also as a level of
protection against accidental writes
> Add the ability to mark an existing tx as read-only

- src/database-layer/db.ts
> Fix certain internal transaction calls triggering read-only violations

- src/database-layer/db.ts
> Share automatic transaction closing between transaction clones

- src/sbvr-api/hooks.ts
> Add support for marking hooks as read-only

- package.json
- src/sbvr-api/hooks.ts
> Add the ability to set sideEffects/readOnlyTx for a set of hooks

- src/sbvr-api/permissions.ts
> Mark permissions hook as read-only

- package.json
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
> Update typescript to 4.x

- src/database-layer/db.ts
- src/sbvr-api/permissions.ts
> Improve async stack traces

- build/browser.ts
- package.json
- src/config-loader/config-loader.ts
- src/express-emulator/express.js
- src/sbvr-api/cached-compile.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
> Make use of optional assignment syntax

- src/migrator/migrator.ts
> Fix overwriting error messages in migrations failures

- src/sbvr-api/odata-response.ts
> Treat deferred foreign key uris as metadata

- README.md
> Update README now that sbvr-compiler/odata-compiler are included

- src/database-layer/db.ts
> Condense starting a read only transaction to a single statement

- src/sbvr-api/sbvr-utils.ts
> Fix logger creation for nodejs 14

- src/config-loader/config-loader.ts
> Leave the migrationsPath intact when loading a model

- Gruntfile.ts
- build/browser.ts
- build/config.ts
- build/module.ts
> Improve compatibility with webpack 5

- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
> Add support for differentiating check constraint errors

- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
> Add support for prettifying check constraints with their description

- bin/abstract-sql-compiler.js
- package.json
- src/bin/abstract-sql-compiler.ts
- src/sbvr-api/sbvr-utils.ts
> Add an abstract-sql-compiler bin helper

- src/bin/abstract-sql-compiler.ts
- src/bin/odata-compiler.ts
- src/bin/sbvr-compiler.ts
- src/bin/utils.ts
> Share code between the cli tools

- src/database-layer/db.ts
> Ensure database connection errors are wrapped as `DatabaseError`s

- src/config-loader/env.ts
- src/database-layer/db.ts
> Enable keepAlive for postgres by default with the ability to disable

- src/database-layer/db.ts
> Error/dequeue all in-progress queries when rolling back a transaction

- src/config-loader/env.ts
- src/database-layer/db.ts
> Handle `TRANSACTION_TIMEOUT_MS` in the env module

- src/config-loader/env.ts
- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
> Handle `DEBUG` in the env module

- src/config-loader/env.ts
- src/database-layer/db.ts
> Add the ability to specify query/statement timeouts for pg backend

- src/sbvr-api/sbvr-utils.ts
> Use 500s for any database errors that are not explicitly handled

- src/sbvr-api/abstract-sql.ts
> Use 400s for data type validation errors

- package.json
- src/sbvr-api/abstract-sql.ts
Update abstract-sql-compiler from 7.8.2 to ???
> Make use of rule specific referenced fields to run rules in less cases

- src/server-glue/server.ts
> Simplify server-glue/server exports

- src/server-glue/server.ts
> Export extended-sbvr-parser from server-glue/server

- src/sbvr-api/sbvr-utils.ts
> Gracefully handle `HttpError` thrown from PREPARSE hooks

- src/sbvr-api/uri-parser.ts
> Warn when setting a `request.values` property that will not take effect

- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
> Remove some unnecessary bluebird usage

- package.json
Update abstract-sql-compiler from 7.11.0 to 7.12.0
> Update abstract-sql-compiler bring more rules optimizations

- src/sbvr-api/sbvr-utils.ts
This fixes an issue where trying to eagerly fetch affected ids for
equests that can create entries would return ids for existing entries
that you could have created rather than giving the ids for the entries
that you will create
> Block eagerly fetching affected ids in cases it is not possible to do

- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
> Support postgres exclusion constraints as 409s instead of 500s

- src/passport-pinejs/passport-pinejs.ts
- src/sbvr-api/express-extension.ts
- src/sbvr-api/permissions.ts
> Expose methods to resolve api keys without immediately using them

- src/sbvr-api/permissions.ts
> Only use the api key if we successfully resolved one

- src/bin/odata-compiler.ts
> Fix typo in odata-compiler help

- Gruntfile.ts
- package.json
- src/bin/abstract-sql-compiler.ts
- src/bin/odata-compiler.ts
- src/bin/sbvr-compiler.ts
- src/bin/utils.ts
- src/database-layer/db.ts
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
Update sbvr-types from 3.4.1 to 3.4.3
> Update sbvr-types to 3.4.3 to support boolean computed terms w/o casting

- docs/ProjectConfig.md
Update user SBVR model URL
Signed-off-by: Matthew Yarmolinsky <matthew-timothy@balena.io>
> Update user SBVR model URL

- docs/AdvancedUsage.md
Fix Hooks URL
Signed-off-by: Matthew Yarmolinsky <matthew-timothy@balena.io>
> Fix Hooks URL

- src/sbvr-api/common-types.ts
- src/sbvr-api/errors.ts
> Reduce duplication for http error constructors

- src/sbvr-api/errors.ts
- src/sbvr-api/sbvr-utils.ts
> Add the ability to include headers with http errors

- src/sbvr-api/sbvr-utils.ts
> Standardize http error to response conversion and response sending

- docs/GettingStarted.md
Fix Minor Typo in GettingStarted.md
Signed-off-by: Matthew Yarmolinsky <matthew-timothy@balena.io>
> Fix Minor Typo in GettingStarted.md

- src/config-loader/config-loader.ts
- src/data-server/sbvr-server.js
- src/express-emulator/express.js
- src/http-transactions/transactions.js
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/server-glue/server.ts
> Use `res.status(...).end()` in preference to `res.sendStatus()`

- src/sbvr-api/permissions.ts
> Avoid unnecessary work when a request's permission type is specified

- src/sbvr-api/sbvr-utils.ts
> Export a `handleHttpErrors` function to handle HttpError/subclasses

- src/sbvr-api/sbvr-utils.ts
> Use readTransaction for read-only requests

- package.json
- src/sbvr-api/sbvr-utils.ts
- tsconfig.json
Fixes tests on master.
Tried to figure out the appropriate check based on the code.
> Update typescript to 4.4

- src/sbvr-api/sbvr-utils.ts
> Avoid iterating the sql result if affectedIds is already populated

- package.json
Update abstract-sql-compiler from 7.13.5 to 7.14.0
> Update abstract-sql-compiler to 7.14.0

- src/database-layer/db.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/permissions.ts
> More usage of nullish coalescing

- src/database-layer/db.ts
> Add the postgres pool error handler even when no PG_SCHEMA is specified

- src/database-layer/db.ts
> Add an error handler to each pg client to prevent any unhandled errors

- src/database-layer/db.ts
> Use the env pool settings as defaults only if not explicitly provided

- src/config-loader/env.ts
> Fix env var name in warning message

- src/migrator/migrator.ts
> Add missing await

- package.json
Update from lf-to-abstract-sql 4.3.0 to 4.4.0
> Update from lf-to-abstract-sql to 4.4.0

- src/config-loader/env.ts
- src/sbvr-api/permissions.ts
> Add the ability to enable caching of api key actor ids

- package.json
Update abstract-sql-compiler from 7.15.0 to 7.17.0
Update lf-to-abstract-sql from 4.4.0 to 4.4.1
Update sbvr-parser from 1.2.5 to 1.3.0
> Update dependencies for improved sbvr negation

- src/config-loader/env.ts
- src/database-layer/db.ts
> Add the ability to set the maxUses for the postgres pool

- src/database-layer/db.ts
- src/server-glue/module.ts
> Improve typings of databaseOptions parameter

- src/sbvr-api/permissions.ts
> Fix permissions using `canAccess` that would fail if target resource specified no filter

- src/config-loader/env.ts
- src/database-layer/db.ts
> Add the ability to set the maxLifetimeSeconds for the postgres pool

- src/database-layer/db.ts
- src/sbvr-api/sbvr-utils.ts
PG Types have added maxUses as key and ts except is not needed any more
> Fixed unneccessary @ts-expect-error

- src/sbvr-api/permissions.ts
- src/sbvr-api/user.sbvr
Change-Type: minor
Signed-off-by: Nitish Agarwal <1592163+nitishagar@users.noreply.github.com>
Spec: https://jel.ly.fish/e450713f-001c-4470-b571-71724aeb0869
See: https://www.flowdock.com/app/rulemotion/resin-tech/threads/vx-rBrpDBqXtkdtMmSU5MmPYSlb
> Add an expiry date to 'api key'

- src/sbvr-api/sbvr-utils.ts
In practice the module level `db.engine` will always match the
`request.engine` but this future proofs things and makes it clear where
this value actually comes from
> Use the db engine from the existing request when getting affected ids

- .dockerignore
- .gitignore
- .resinci.yml
- Dockerfile
- docker-compose.test.yml
- docker-compose.yml
- docs/GettingStarted.md
- docs/Testing.md
- package.json
- repo.yml
- test/00-basic.test.ts
- test/01-constrain.test.ts
- test/fixtures/00-basic/config.ts
- test/fixtures/00-basic/example.sbvr
- test/fixtures/01-constrain/config.ts
- test/fixtures/01-constrain/university.sbvr
- test/lib/pine-in-process.ts
- test/lib/pine-init.ts
- test/lib/test-init.ts
Addind mocha, ts-node and chai to  pinejs.
Utilising docker-compose to handle test requirements like postgres db
> inital test framework for pinejs

- src/sbvr-api/sbvr-utils.ts
> Simplify check for read-only hooks

- src/sbvr-api/permissions.ts
> Use the modern definition format for permission constrained definitions

- src/sbvr-api/permissions.ts
> Only remove constrained aliases when they match the field name

- package.json
> Update typescript to 4.7

- src/config-loader/env.ts
- src/sbvr-api/permissions.ts
See: https://www.flowdock.com/app/rulemotion/resin-tech/threads/H1xvtNzl8i5atMElV51nix3uWGf
> permissions: Add optional transaction param to user & api key methods

- package.json
Update @balena/odata-to-abstract-sql from 5.4.11 to 5.4.12
> Update @balena/odata-to-abstract-sql to 5.4.12

- src/sbvr-api/hooks.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
> Allow PRERESPOND hooks to modify the response

- src/sbvr-api/permissions.ts
This changes the bypass to only occur before guest permissions are
initialized, only when specifically using `root` or `rootRead`
permissions, and also now constrains the model to the specific
permissions passed in rather than bypassing permissions altogether
for the root cases
> Narrow the scope of the permissions bypass for root permissions

- src/config-loader/config-loader.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
> Convert lodash `isObject` usage to native versions

- src/config-loader/config-loader.ts
- src/data-server/sbvr-server.js
- src/database-layer/db.ts
- src/http-transactions/transactions.js
- src/odata-metadata/odata-metadata-generator.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
> Prefer for..of over forEach

- src/sbvr-api/permissions.ts
> Fix synonyms iteration

- .github/workflows/flowzone.yml
- .resinci.yml
> Replace balena ci with flowzone

- .github/workflows/flowzone.yml
> Enable flowzone branch protection

- .github/workflows/flowzone.yml
> Remove docker hub credentials from flow zone job

- docs/GettingStarted.md
> Docs: Fix TypeScript getting started example

- docs/AdvancedUsage.md
> Docs: Update/fix advanced usage doc

- docs/GettingStarted.md
> Docs: Update/fix getting started doc

- docs/ProjectConfig.md
> Docs: Update/fix project config doc

- package.json
> Update @balena/abstract-sql-compiler from 7.20.0 to 7.21.0

- src/migrator/async.ts
> Fix async migrations being able to stop unexpectedly in some failure cases

- docs/Testing.md
> Update debugging docs

- src/sbvr-api/permissions.ts
> Simplify `checkApiKey` by moving checks out to more relevant places

- package.json
- src/migrator/async.ts
> Fix running linting as part of `npm test`

- src/sbvr-api/odata-response.ts
- src/sbvr-api/sbvr-utils.ts
> Prettified according to new rules

- src/sbvr-api/permissions.ts
> Handle symbols when proxying for constrained models

- package.json
Update @balena/abstract-sql-compiler from 7.25.0 to 7.25.3
> Update @balena/abstract-sql-compiler to 7.25.3

- src/config-loader/config-loader.ts
- src/data-server/sbvr-server.js
- src/http-transactions/transactions.js
- src/sbvr-api/permissions.ts
- src/server-glue/module.ts
- src/server-glue/server.ts
> Remove duplicate stack trace logging

- Dockerfile
- package.json
This reverts commit 6b85dd0063669e7db4432bdb650927d05ef9f9c4.
> Revert "chore(deps): update node.js to v19"

- src/bin/odata-compiler.ts
- src/config-loader/config-loader.ts
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/translations.ts
- src/sbvr-api/uri-parser.ts
TODO: Should add tests to both prove the behavior works and as an example of how to use the translations
See: https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/native.20translations
> Add support for models that are translated to other (newer) models

- src/sbvr-api/hooks.ts
> Fix read-only hook args when there is a read-only or no transaction

- src/migrator/async.ts
- test/03-async-migrator.test.ts
- test/fixtures/03-async-migrator/01-migrations/migrations/0003-finalized-test-migration.async.ts
> Fixes setting only finalized async migration as executed

- src/migrator/utils.ts
> Fix `isAsyncMigration` to accept mixed fn and sql async migrations

- src/database-layer/db.ts
- src/migrator/async.ts
Disable automaticClose on async mgmt tx
> Rollback async migration tx on failed async mgmt tx

- src/sbvr-api/translations.ts
> Guard against translations aliasing to a field that does not exist

- docs/Migrations.md
> Migrations.md: Add marking the sbvr field as optional on the 2nd deploy

- package.json
- src/migrator/utils.ts
> Update TypeScript to 5.1.3

- src/migrator/sync.ts
- src/migrator/utils.ts
> Fix pinejs 15 migrations for the migrations model

- package.json
Update pinejs-client-core from 6.12.3 to 6.13.0
> Update pinejs-client-core to 6.13.0

- src/sbvr-api/sbvr-utils.ts
Throw a Bad Request error when passing unknown vocabulary in a request
Connects-to: #675 
> Throw a Bad Request error when passing unknown vocabulary in a request

- src/sbvr-api/sbvr-utils.ts
Return a response even when the request resolves to an HTTP error
Connects-to: #675 
> Return a response even when the request resolves to an HTTP error

- src/bin/abstract-sql-compiler.ts
- src/bin/odata-compiler.ts
- src/bin/sbvr-compiler.ts
See: https://github.com/balena-io/pinejs/pull/682#discussion_r1304255389
> bin: Use async imports in compile-schema and generate-types cli commands

- src/webresource-handler/index.ts
- test/06-webresource.test.ts
> Fix webresource patch on not accessible/inexistent key

- src/webresource-handler/handlers/S3Handler.ts
> Change S3Handler signing config from private to protected

- src/webresource-handler/index.ts
- test/06-webresource.test.ts
> Fix failure on delete requests with invalid ID

- package.json
Depends-on: https://github.com/balena-io/pinejs/pull/682
> Update TypeScript to 5.2.2

- src/webresource-handler/index.ts
> Allow uploading file on resourceName and synonyms

- src/webresource-handler/handlers/S3Handler.ts
> Do not force storage class on s3 upload

- package.json
Afterwards use as Alias or ReferencedFields
> Actually compute computed terms only once.

- package.json
> Update TypeScript to 5.3.2

- src/webresource-handler/index.ts
> Remove unnecessary async on busboy file handler

- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/uri-parser.ts
- src/webresource-handler/index.ts
> Remove unnecessary `async` on `parseOData`

- src/sbvr-api/translations.ts
> Fix nested translations

- src/sbvr-api/uri-parser.ts
> Check that some fields are being updated for PATCH requests

- src/config-loader/config-loader.ts
- src/migrator/async.ts
- src/migrator/sync.ts
- src/odata-metadata/odata-metadata-generator.ts
- src/passport-pinejs/mount-login-router.ts
- src/sbvr-api/abstract-sql.ts
- src/sbvr-api/common-types.ts
- src/sbvr-api/hooks.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/sbvr-api/translations.ts
- src/server-glue/module.ts
- src/webresource-handler/handlers/NoopHandler.ts
- src/webresource-handler/handlers/S3Handler.ts
- src/webresource-handler/index.ts
- test/03-async-migrator.test.ts
- test/04-translations.test.ts
---
Just adding missing type imports I noticed while working on something else
> Improve type imports by using "import type" where possible

- test/02-sync-migrator.test.ts
- test/03-async-migrator.test.ts
- test/fixtures/02-sync-migrator/01-migrations/0002-test-migrations.sync.ts
- test/fixtures/02-sync-migrator/02-migrations-error/0002-test-migrations.sync.ts
- test/fixtures/03-async-migrator/01-migrations/migrations/0002-test-migrations.async.ts
- test/fixtures/03-async-migrator/01-migrations/migrations/0003-finalized-test-migration.async.ts
- test/fixtures/03-async-migrator/02-parallel-migrations/migrations/0001-migrate-testa.async.ts
- test/fixtures/03-async-migrator/02-parallel-migrations/migrations/0002-migrate-testb.async.ts
- test/fixtures/03-async-migrator/03-finalize-async/migrations/m0001-data-copy.async.ts
- test/fixtures/03-async-migrator/03-finalize-async/migrations/m0002-data-copy.async.ts
- test/fixtures/03-async-migrator/04-migration-errors/migrations/0001-successful-migration.async.ts
- test/fixtures/03-async-migrator/04-migration-errors/migrations/0002-table-not-exists.async.ts
- test/fixtures/03-async-migrator/04-migration-errors/migrations/0003-error-unique-key.async.ts
- test/fixtures/03-async-migrator/05-massive-data/migrations/0001-massive-migration.async.ts
- test/fixtures/03-async-migrator/06-setup-errors/0001-error-async-sync-pair.async.ts
- test/fixtures/04-translations/config.ts
- test/fixtures/04-translations/translations/v1/index.ts
- test/fixtures/04-translations/translations/v2/index.ts
- test/fixtures/04-translations/translations/v3/index.ts
- test/fixtures/05-request-cancellation/routes.ts
- test/fixtures/06-webresource/config.ts
- test/fixtures/06-webresource/translations/v1/index.ts
- test/lib/pine-in-process.ts
- test/lib/test-init.ts
> Fix linting with proper import type

- package.json
- src/migrator/utils.ts
> Use a type guard for `"migration"."migration status"`

- package.json
Update @balena/odata-to-abstract-sql from 6.2.3 to 6.2.7
> Update @balena/odata-to-abstract-sql to 6.2.7

- package.json
> Tests: trap `INT` rather than `SIGINT` for broader shell support

- src/bin/sbvr-compiler.ts
> Avoid duplicate types when using sbvr-compiler to generate model types

- src/sbvr-api/hooks.ts
- src/sbvr-api/odata-response.ts
- src/sbvr-api/sbvr-utils.ts
> Improve `result` typing for `POSTRUN`/`PRERESPOND` hooks

- test/04-translations.test.ts
> Improve test assertion for not undefined

- src/bin/utils.ts
- src/config-loader/config-loader.ts
Found it while filtering some logs while a deploy was taking place.
> Fix unrecognized migration & config typo

- package.json
- src/webresource-handler/index.ts
> Update TypeScript to 5.5.2

- src/database-layer/db.ts
---
This is a prerequisite for https://github.com/balena-io/pinejs/pull/739 as we want to allow task transactions to stay open longer than others
> Add transaction timeoutMS override option

- src/passport-pinejs/passport-pinejs.ts
- src/sbvr-api/sbvr-utils.ts
- src/server-glue/module.ts
- src/webresource-handler/index.ts
> Remove unnecessary async/await statements

- test/fixtures/04-translations/translations/hooks.ts
- test/fixtures/06-webresource/translations/hooks.ts
> Tests: avoid unnecessarily asynchronous imports

- build/browser.ts
- build/module.ts
- build/server.ts
- src/config-loader/config-loader.ts
- src/migrator/async.ts
- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- src/server-glue/server.ts
> Fix some lint warnings

- src/sbvr-api/sbvr-utils.ts
> Throw an UnauthorizedError on /canAccess requests for unknown resources

- src/sbvr-api/translations.ts
- src/sbvr-api/uri-parser.ts
- test/fixtures/04-translations/config.ts
- test/fixtures/04-translations/translations/v3/index.ts
- test/fixtures/04-translations/translations/v4/index.ts
- test/fixtures/04-translations/translations/v4/university.sbvr
- test/fixtures/04-translations/translations/v5/index.ts
- test/fixtures/04-translations/translations/v5/university.sbvr
> Clarify the intention of `request.resourceName` and fix issues related to mismatched expectations

- test/04-translations.test.ts
> Tests: stop using deprecated `faker` functions

- src/sbvr-api/translations.ts
This matches closer with the idea of a stage by stage translation where you translate as if you were a a request against the next model, then that translates to the next model and so on
> Translations: prefer translating to the unaliased resource of the target model

- src/sbvr-api/permissions.ts
This also fixes the returned actor id for `checkPassword` since the improved typings caught that it did not match the expected return type
> Use updated pinejs-client `prepare` syntax

- src/http-transactions/transactions.js
> Avoid deprecated usage of pinejs-client

- package.json
- src/sbvr-api/sbvr-utils.ts
> Update pinejs-client-core to 8.x

- package.json
Update @balena/sbvr-types from 9.0.1 to 9.0.2
> Update @balena/sbvr-types from 9.0.1 to 9.0.2

- docker-compose.npm-test.yml
- src/webresource-handler/index.ts
> Fix large webresource test race condition

- src/sbvr-api/permissions.ts
- src/sbvr-api/sbvr-utils.ts
- test/07-permissions.test.ts
> Add getAuthCompiler for building permissions

- src/tasks/worker.ts
- test/08-tasks.test.ts
- test/lib/common.ts
- test/lib/pine-in-process.ts
> Add tasks worker `stop` method

- src/database-layer/db.ts
- src/sbvr-api/cached-compile.ts
- src/sbvr-api/uri-parser.ts
- src/webresource-handler/index.ts
- test/08-tasks.test.ts
> Linting fixes

- src/tasks/index.ts
> Expose tasks model on sbvrUtils api

- test/lib/pine-in-process.ts
- test/lib/pine-init.ts
- test/lib/test-init.ts
> Add ability to run tests with cluster mode

- docker-compose.npm-test.yml
- package.json
> Run tests on UTC TZ

- package.json
- src/sbvr-api/permissions.ts
> Update typescript from 5.6.3 to 5.7.2

- src/data-server/sbvr-server.ts
> Remove jsdoc typings from typescript file

- docs/Migrations.md
> Migrations.md: Update the rollbackable migrations guide

- package.json
- src/sbvr-api/abstract-sql.ts
Update @balena/abstract-sql-compiler from 10.1.0 to 10.2.0
Update @balena/odata-parser from 3.1.2 to 4.1.0
Update @balena/odata-to-abstract sql from 7.0.1 to 7.1.0
See: https://balena.fibery.io/search/rLsEn#Work/Project/Pinejs-$in-as-a-single-bind-895
> Compile in as `(= ANY($singleListBinding))`

- src/migrator/async.ts
- src/sbvr-api/sbvr-utils.ts
> Free up migration related memory after the models get executed

- src/tasks/worker.ts
> Tasks: add a 100ms retry delay after a failed poll

- package.json
- src/bin/utils.ts
- src/data-server/sbvr-server.ts
- src/database-layer/db.ts
- src/express-emulator/express.js
- src/sbvr-api/cached-compile.ts
- src/sbvr-api/control-flow.ts
- src/sbvr-api/hooks.ts
- src/tasks/index.ts
- src/tasks/worker.ts
- src/webresource-handler/handlers/NoopHandler.ts
- src/webresource-handler/index.ts
- test/fixtures/08-tasks/task-handlers.ts
- test/lib/pine-in-process.ts
> Fix some linting issues

- package.json
- src/tasks/index.ts
- test/08-tasks.test.ts
> Update cron-parser to v5

- package.json
Update @balena/odata-to-abstract-sql from 7.1.6 to 7.2.0
Depends-on: https://github.com/balena-io-modules/odata-to-abstract-sql/pull/166
See: https://balena.fibery.io/Work/Project/Shape--Build-Add-support-for-sorting-on-user-selected-tag-columns-in-the-server-side-paginated-devic-912
> Support $orderby based on a unique reverse navigation resource

- package.json
- src/config-loader/env.ts
- src/database-layer/db.ts
> Postgres: add the option to prepare db queries after N executions

- test/06-webresource.test.ts
> Add test for webresource rule on patches

- test/06-webresource.test.ts
See: https://balena.fibery.io/search/tyKzx#Work/Improvement/Make-webresources-file-deletion-more-reliable-2819
> Improve webresource tests

- test/06-webresource.test.ts
See: https://balena.fibery.io/search/tyKzx#Work/Improvement/Make-webresources-file-deletion-more-reliable-2819
> Improve webresource tests to be independent of filename

- src/tasks/index.ts
- src/tasks/pine-tasks.ts
- src/webresource-handler/delete-file-task.ts
- src/webresource-handler/index.ts
- test/06-webresource.test.ts
See: https://balena.fibery.io/search/bGknx#Work/Improvement/Make-webresources-file-deletion-more-reliable-2819
> Delete files with pine tasks when it is available

- package.json
Update @balena/abstract-sql-to-typescript from 5.1.1 to 5.1.2
> Bump @balena/abstract-sql-to-typescript to v5.1.2

- package.json
- src/sbvr-api/sbvr-utils.ts
Update @balena/abstract-sql-compiler from 10.3.3 to 10.4.0
> Optimize the abstract-sql schema whilst creating it

- package.json
- src/sbvr-api/sbvr-utils.ts
- src/webresource-handler/actions/beginUpload.ts
- src/webresource-handler/index.ts
- test/06-webresource.test.ts
Update pinejs-client-core from 8.2.0 to 8.3.0
Update pinejs-client-supertest from 3.0.1 to 3.1.0
> Bump pinejs-client-core to v8.3.0
