migrations/8.3.0-fix-migration-primary-key.sql, package.json, src/config-loader/env.ts, src/migrator/migrations.sbvr, src/migrator/migrator.ts
Depends on https://github.com/resin-io/lf-to-abstract-sql/pull/21
=> Add a migrations lock so only one pinejs instance will run migrations

src/config-loader/config-loader.ts
This fixes issues with requiring when it's a relative path
=> Resolve the root argument as an absolute path

src/database-layer/db.ts
The generated code is identical to before as the values were hardcoded to match for both (they're required to match), but this just lets typescript enforce that
=> Use the Engines enum for engines names to guarantee consistency

src/sbvr-api/sbvr-utils.ts
=> Fix `data` parameter passed to GET PRERESPOND hooks

src/database-layer/db.ts
=> Correctly propagate transaction creation errors in `db.transaction(fn)`

package.json, src/sbvr-api/permissions.ts
Update abstract-sql-compiler from 6.7.0 to 6.7.1
Update pinejs-client-core from 5.5.1 to 5.5.4
=> Fix missing `promise: true` option for memoized `$getApiKeyPermissions`

src/sbvr-api/odata-response.ts
It provides no useful info and just increases gc, JSON.stringify, and
bandwidth costs
=> Stop sending `type` in the response as it's always an empty string

src/sbvr-api/odata-response.ts, src/sbvr-api/sbvr-utils.ts
=> Don't generate a `resourceURI` if there is no resource id

src/sbvr-api/control-flow.ts
This fixes issues where `err.message` is not a string
=> Accept `instanceof Error` as valid errors

src/sbvr-api/uri-parser.ts
These have enough potential permutations to use up the cache space
for marginal benefit
=> Avoid caching odata urls with a hardcoded key parameter

src/sbvr-api/permissions.ts, src/sbvr-api/sbvr-utils.ts
Invocation of actor ID lookup by api key is moved upstream,
so it can be stored on the apiKey object and reused.
This way, we can use actor ID in both session tokek and api key
authentication cases without extra DB query.
Signed-off-by: Roman Mazur <roman@balena.io>
=> permissions: Set actor on api key

package.json, src/sbvr-api/permissions.ts
This will allow to write simpler permissions, which point
to access depending on other resources access.
Depends-On: https://github.com/balena-io-modules/odata-parser/pull/45
Depends-On: https://github.com/balena-io-modules/odata-to-abstract-sql/pull/48
=> ✨: Add support for `canAccess()` function in permission.

src/sbvr-api/permissions.ts
We don't want to allow circle permissions using the `canAccess()` marker.
=> ♻️ : Dissallow circle permissions with `canAccess()`

package.json, src/sbvr-api/permissions.ts, src/sbvr-api/sbvr-utils.ts
When a permission uses the `canAccess()` function to derive access,
to another resource, we can optimize the generated SQL queries to not,
reapply the full permission for resources, that are reached by
expanding or filtering paths. We achieve this by, applying shortcuts
in the relationships of the abstract sql model, if we find usages of
an `canAccess()` function in the relevant permissions, that link the
resources in the correct direction.
An example:
Let's imagine a model where a `device` belongs to an `application`.
We have the following permissions:
```
example.application.get?belongs_to__user/any(u:u/actor eq @__ACTOR_ID)
example.device.get?belongs_to__application/canAccess()
```
Given the following odata query:
```
GET /example/application?$select=id,name&$filter=(owns__device/any(d: …
```
=> ✨: Optimize database queries for `canAccess()` permissions

package.json, src/sbvr-api/permissions.ts
Update abstract-sql-compiler from 7.4.1 to 7.4.2
Update odata-to-abstract-sql from 5.4.0 to 5.4.1
Depends-on: https://github.com/balena-io-modules/abstract-sql-compiler/pull/102
Depends-on: https://github.com/balena-io-modules/odata-to-abstract-sql/pull/70
=> Update abstract-sql-compiler to 7.4.2

.npmrc
Just like we do in pine-client. Atm a no-op since we do not have a pakcage-lock in the repo at all.
=> Disable the creation of a package-lock on each npm install

src/sbvr-api/permissions.ts
Instantiating an `OData2AbstractSQL` instance can be relatively costly
and as such reusing a memoized instance can provide a reasonable
performance improvement
=> Optimize generating constrained abstract sql model

package.json
Update abstract-sql-compiler from 7.10.0 to 7.10.1
Update sbvr-types from 3.1.3 to 3.2.0
=> Update sbvr-types to 3.2.0, adding support for more `Text (Type)` verbs

package.json
Update abstract-sql-compiler from 7.12.0 to 7.13.0
=> Update abstract-sql-compiler to 7.13.0 to support CurrentTimestamp/Date

package.json
Update lf-to-abstract-sql from 4.2.2 to 4.3.0
See: https://github.com/balena-io-modules/lf-to-abstract-sql/pull/47
See: https://www.flowdock.com/app/rulemotion/platform/threads/hnT7FJDke0tWpsNrF7OfX2-bSMY
=> Bump dependencies to add `is of` reverse relationship for concept types

docs/GettingStarted.md
Add quotes for single entity curl requests
`curl` requests were failing when accessing endpoints with ids e.g. `curl -X GET http://localhost:1337/example/device(3)`. Quoting such endpoints resolved the issue e.g. `curl -X GET "http://localhost:1337/example/device(3)"`
Signed-off-by: Muizudeen Kusimo <muizz@balena.io>
=> Add quotes for single entity curl requests

src/database-layer/db.ts, src/sbvr-api/common-types.ts
=> Add method for getting transaction level advisory locks in Postgresql

src/sbvr-api/hooks.ts
=> Avoid creating a new readOnlyArgs object when args is already read-only

build/browser.ts, src/config-loader/env.ts
This means we can warn on/ignore invalid values rather than giving a
potentially surprising result, eg `'0'` being truthy
=> Add support for a `PINEJS_DEBUG` env var that is more strictly checked

package.json
Update @balena/abstract-sql-compiler from 7.17.1 to 7.18.0
Update @balena/lf-to-abstract-sql from 4.4.1 to 4.5.0
Update @balena/sbvr-parser from 1.3.0 to 1.4.0
=> Update dependencies for referenceType

src/passport-pinejs/passport-pinejs.ts
passport.js 0.6.0 introduces a mandatory callback done function.
Updated logout argument which should remain backwards compatible
=> Fix for passport.js update 0.6.0

package.json, src/migrator/sync.ts, src/migrator/utils.ts, src/sbvr-api/sbvr-utils.ts, test/02-sync-migrator.test.ts, test/fixtures/02-sync-migrator/04-new-model-with-init.ts, test/fixtures/02-sync-migrator/example.sbvr
Modules may need to know if a model existed before initialisation of the instance.
Eg. migrations need to know if a model is freshly generated / executed
of if this model already existed and can be target for migrations.
=> Refactor checkModelExists to isModelNew

src/sbvr-api/abstract-sql.ts, src/sbvr-api/hooks.ts, src/sbvr-api/sbvr-utils.ts, src/sbvr-api/uri-parser.ts
This allows us to make properties on the process odata request required
whereas previously they had to be optional in order to be compatible,
as of now this only affects the `engine` property but in future further
properties of the processed request could be made required. And even at
this point it will block passing a parsed only request object to a
function expecting a processed request object
=> Differentiate typings between parsed and processed odata requests

src/config-loader/env.ts, src/database-layer/db.ts
This removes a cost per query which is generally unnecessary and can
add up to being significant in read heavy workloads
=> Make checking that read-only TX queries are SELECT queries optional

src/sbvr-api/permissions.ts
Inferenced type of check could be I & null
when I is not set in the overload.
Issue reported:
```
Using tsc v4.8.2
src/sbvr-api/permissions.ts(225,34): error TS2769: No overload matches this call.
Overload 1 of 2, '(o: {}): string[]', gave the following error.
Argument of type 'NestedCheckOr<I> | NestedCheckAnd<I> | (I & object) | (I & null)' is not assignable to parameter of type '{}'.
Type 'I & null' is not assignable to type '{}'.
Overload 2 of 2, '(o: object): string[]', gave the following error.
Argument of type 'NestedCheckOr<I> | NestedCheckAnd<I> | (I & object) | (I & null)' is not assignable to parameter of type 'object'.
Type 'I & null' is not assignable to type 'object'.
>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:default" failed. Use …
```
=> Fixing issue reported by tsc 4.8.2

package.json
It is already run as part of the tests which are required by CI before it'll publish, and avoids issues when publishing without dev deps
=> Remove prepublishOnly lint step

docs/GettingStarted.md
Give preference to TypeScript over CoffeeScript for the example app. Improve code blocks by giving them types and removing unnecessary characters to better enable copy-paste when viewing on GitHub.
=> Docs: Improve getting started doc

package.json
Update pinejs-client-core from 6.10.2 to 6.12.2
=> Support `$count: { $filter: {...} }` notation in $filter & $orderby

package.json, src/sbvr-api/permissions.ts, src/sbvr-api/uri-parser.ts
Update @balena/odata-to-abstract-sql from 5.5.0 to 5.6.0
=> Use minimized aliases when not in debug mode for smaller queries

src/sbvr-api/hooks.ts
This avoids unnecessary work by adding an async boundary for the filtering part, meaning we can avoid any async boundaries in the case of no side effecting hooks (the likely case)
=> Filter for `SideEffectHook`s before entering the async rollback loop

src/config-loader/env.ts, src/database-layer/db.ts, src/migrator/async.ts, src/migrator/sync.ts, src/migrator/utils.ts, src/server-glue/module.ts, test/03-async-migrator.test.ts, test/fixtures/03-async-migrator/08-01-async-lock-taker.ts, test/fixtures/03-async-migrator/08-02-sync-lock-starvation.ts
Avoid starvation of sync migrations while
aggressive async migrations take the model lock
over and over again.
=> Use postgres advisory locks for migration locking.

src/database-layer/db.ts
That's already how it works b/c the only concrete implementation default to true, so this is more as a way to make the base class typings mark this as an optional parameter having a default value.
Otherwise users would get a  TS error after updating.
See: https://github.com/balena-io/open-balena-api/actions/runs/4004587439/jobs/6873921096
=> db: Make the base getTxLevelLock blocking by default

package.json, src/config-loader/env.ts, src/migrator/async.ts, test/03-async-migrator.test.ts, test/fixtures/03-async-migrator/01-migrations/migrations/0002-test-migrations.async.ts, test/lib/pine-init.ts
Introduce env var PINEJS_ASYNC_MIGRATION_ENABLED to control async migration execution on startup. Introduce SIGUSR2 listener to toggle migration execution during runtime.
=> Introduce control means for async migration execution

package.json, src/sbvr-api/sbvr-utils.ts
Signed-off-by: Carol Schulze <carol@balena.io>
=> Use `affectedIds` to narrow the number of rows checked by rules

src/sbvr-api/permissions.ts
Permissions lookup need to know the modifyName if the resource needs translations for looking up the permissions from the destination permissions table
=> Fix resourceName to resourceName native translation

src/sbvr-api/permissions.ts
---
Recent type changes in `abstract-sql-compiler` broke pinejs typescript builds, updating typings to get builds working again.
=> Update select sql typing

src/config-loader/config-loader.ts
app.all registers too many not needed HTTP methods. As documented here:
https://expressjs.com/en/4x/api.html#app.METHOD
=> Narrow the registered express HTTP methods

src/migrator/async.ts, src/migrator/utils.ts
This also deprecates the form of returning a db result
=> Support returning a number from async migrations rather than db result

src/sbvr-api/hooks.ts
=> Mark that `tx` is always passed to `POSTRUN-ERROR` hooks

src/migrator/sync.ts, src/migrator/utils.ts, src/sbvr-api/sbvr-utils.ts, src/server-glue/module.ts, test/03-async-migrator.test.ts
On empty database schemas the `migrations` model is not executed. Hence, every model migration that is executed before the `migrations` model will not be tracked properly. This is an edge case for empty database schemas.
=> Fix skipped migrations on empty database schema

README.md, src/config-loader/config-loader.ts, src/sbvr-api/odata-response.ts, src/webresource-handler/handlers/S3Handler.ts, src/webresource-handler/index.ts, test/06-webresource.test.ts
Context: When serving webresources we may need aditional postprocessing (e.g. signing the URL). This was previously done with a PRERESPONSE hook on the model that had a webresource. 
The problem with this approach is that one model that does not contain a webresource can be $expand on a field that contains a webresource and then the GET hook won't be setup and postprocessing (presigning) won't occur.
This PR solves the issue by presigning a level deeper into the stack. When we fetch a resource from the DB that is a webresource, we postprocess as a webresource will never be served without the postprocessing.
=> Fix $expand on parent resource with child webresource

src/database-layer/db.ts
rowCount can be NULL in the case of PG returning from `LOCK`
Refernece:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66990 https://github.com/brianc/node-postgres/pull/2967
In pinejs the case is handled and as of now we don't want to populate a breaking change by transparently push the types to callers.
=> Handling typing changes of @types/pg

docker-compose.npm-test.yml
These will automatically be started by subsequent test commands as necessary and this will avoid them being unnecessarily started even after a reboot or similar when they are not necessary
=> Tests: Remove restart=always policy for sidecar containers

src/migrator/async.ts, src/migrator/utils.ts
=> Fix `migration` and `migration status` typings.

package.json, src/sbvr-api/sbvr-utils.ts
Depends-on: https://github.com/balena-io-modules/abstract-sql-compiler/pull/237
See: https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/Pine.20Partial.20UNIQUE.20Index.20based.20rules
=> Add support for prettifying index constraint errors with their description

src/http-transactions/transactions.js, src/migrator/async.ts, src/migrator/sync.ts, src/sbvr-api/abstract-sql.ts, src/sbvr-api/permissions.ts, src/sbvr-api/sbvr-utils.ts, src/sbvr-api/uri-parser.ts, src/webresource-handler/index.ts
=> Deprecate LoggingClient in favor of a separate logger dictionary

src/bin/abstract-sql-compiler.ts, src/bin/odata-compiler.ts, src/bin/utils.ts, test/fixtures/04-translations/config.ts, test/fixtures/04-translations/translations/v1/index.ts, test/fixtures/04-translations/translations/v2/index.ts, test/fixtures/04-translations/translations/v3/index.ts, test/fixtures/06-webresource/translations/v1/index.ts
This allows choosing which model to use when the config file contains multiple models
=> odata/abstract-sql-compiler: Add support for specifying the model name for config files

src/sbvr-api/sbvr-utils.ts
500 internal request error is far more accurate to the reality than a 404 not found, and removing the error message also adds safety to these unexpected errors
=> Convert unknown errors to 500 errors rather than 404 for clarity

package.json
Change-type: major
---
Updating as a major as this version of sbvr-types includes breaking changes for BigInt and BigSerial that we pass down to our consumers.
=> Update sbvr-types to v9.0.1

src/config-loader/env.ts
This allows consumers to enable debug mode
only for a single test case, reducing the
amount of noise in their logs.
This allows consumers to for example print the SQL run during a specific test case, by doing
```ts
it('tests something', function () {
const { env: { TEST_MOCK_ONLY } } = await import('@balena/pinejs');
TEST_MOCK_ONLY.DEBUG = true;
// ... tests here
TEST_MOCK_ONLY.DEBUG = false;
});
```
=> Allow changing pine's DEBUG mode on runtime when env.DEPLOYMENT=TEST

src/sbvr-api/permissions.ts
This allows for custom api key handlers that don't rely on `resolveAuthHeader` or `resolveApiKey`
=> Expose `checkApiKey` to allow resolving an api key string

package.json
Update @balena/abstract-sql-compiler from 10.0.1 to 10.1.0 
Update @balena/sbvr-types from 9.0.2 to 9.1.0
=> Update dependencies to support `is case insensitively equal to`

src/tasks/worker.ts, test/08-tasks.test.ts, test/fixtures/08-tasks/example.sbvr, test/fixtures/08-tasks/task-handlers.ts
=> Fix async tasks race condition for selecting task to be executed

src/sbvr-api/abstract-sql.ts, test/01-constrain.test.ts
In previous commit `bdb34d` the code path for `getAndCheckBindValues` was simplified considering the declared type of `{dataType: string}`. That typing is not complete and thus the simplification was wrong.
The field property may also contain a `required` property which is used for doing oData validation (from sbvr-types) In that simplification we excluded the required information for bound variables: https://github.com/balena-io/pinejs/commit/bdb34d9df39e0d9d00db492cbb1ef6dfc61e8450#diff-abade937407ef92d95cd36b5719e481229475da7d3f8bdc613bebef8971c35d2R107
This reverts back the code simplification but keeping the necessary changes for List binding type.
=> Fix missing required validation on bindings

docker-compose.npm-test.yml
These settings are not safe for data we care about as we might lose or corrupt data in the case of power failure, but for test data where that is not an issue they offer a performance benefit
=> Tests: use faster config for postgres

package.json
Update @balena/odata-to-abstract-sql from 7.1.4 to 7.1.6
Depends-on: https://github.com/balena-io-modules/odata-to-abstract-sql/pull/160
=> Update @balena/odata-to-abstract-sql to 7.1.6

src/webresource-handler/index.ts
This PR only adds the optional multipart payload on the webresource handler. Handlers can (or not) implement this functionality and pinejs should be able to deal with both cases. Each handler has its own tests on its own repo, for a implementation reference see here: https://github.com/balena-io-modules/pinejs-webresource-s3/pull/8
See: https://balena.fibery.io/search/PtK6F#Work/Improvement/Add-multipart-upload-interface-for-webresource-handlers-and-add-them-to-S3-Cloudfront-handlers-2584
=> Add multipart upload interface for handlers

src/sbvr-api/translations.ts
This should reduce the size of the generated SQL and hence the memory usage by cache and network usage to transmit the queries
=> Translations: avoid fully referenced fields when not necessary

src/sbvr-api/translations.ts
This avoids unnecessary indirection in the generated SQL for this case and so will reduce the size of the generated SQL and hence the memory usage by cache and network usage to transmit the queries
=> Translations: simplify the generated definition when only `$toResource` is provided

package.json, src/sbvr-api/permissions.ts
This avoids the need to manually reference each field and shrinks the permissions SQL and makes the intent clearer/more understandable
=> Permissions: simplify the constrained abstract sql by using `SELECT *`
